apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-server
  namespace: jenkins-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-server
  template:
    metadata:
      labels:
        app: jenkins-server
    spec:
      #serviceAccountName: jenkins-admin
      securityContext:
        fsGroup: 0
        runAsUser: 0
      containers:
        - name: jenkins-server
          image: jenkins/jenkins:lts
          volumeMounts:
          - name: jenkins-home
            mountPath: /var/jenkins_home
          ports:
          - name: httpport
            containerPort:  8080
          - name: jnlpport
            containerPort: 50000
          livenessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-claim