apiVersion: v1
kind: Service
metadata:
  name: jenkins-server-svc
  namespace: jenkins-namespace
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  type: LoadBalancer
  selector:
    app: jenkins-server
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080